language: node_js

node_js:
  - 6
  - 8
  - 10
  - 11

before_install:
  - npm install -g npm@latest

install:
  - npm ci

script: npm run test:ci

cache:
  directories:
    - $(npm config get prefix)/bin
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.npm
